mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" braFlo1 | grep -l --label=braFlo1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" ci2 | grep -l --label=ci2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" strPur2 | grep -l --label=strPur2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" anoGam1 | grep -l --label=anoGam1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" apiMel2 | grep -l --label=apiMel2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" droAna2 | grep -l --label=droAna2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" droEre1 | grep -l --label=droEre1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" droGri1 | grep -l --label=droGri1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" dm3 | grep -l --label=dm3 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" droMoj2 | grep -l --label=droMoj2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" droPer1 | grep -l --label=droPer1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" dp3 | grep -l --label=dp3 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" droSec1 | grep -l --label=droSec1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" droSim1 | grep -l --label=droSim1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" droVir2 | grep -l --label=droVir2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" droYak2 | grep -l --label=droYak2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" bosTau4 | grep -l --label=bosTau4 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" calJac1 | grep -l --label=calJac1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" canFam2 | grep -l --label=canFam2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" cavPor3 | grep -l --label=cavPor3 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" equCab2 | grep -l --label=equCab2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" felCat3 | grep -l --label=felCat3 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" hg18 | grep -l --label=hg18 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" rheMac2 | grep -l --label=rheMac2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" monDom4 | grep -l --label=monDom4 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" mm9 | grep -l --label=mm9 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" ornAna1 | grep -l --label=ornAna1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" panTro2 | grep -l --label=panTro2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" ponAbe2 | grep -l --label=ponAbe2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" rn4 | grep -l --label=rn4 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" sacCer1 | grep -l --label=sacCer1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" anoCar1 | grep -l --label=anoCar1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" danRer5 | grep -l --label=danRer5 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" galGal3 | grep -l --label=galGal3 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" gasAcu1 | grep -l --label=gasAcu1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" oryLat2 | grep -l --label=oryLat2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" petMar1 | grep -l --label=petMar1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" taeGut1 | grep -l --label=taeGut1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" fr2 | grep -l --label=fr2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" tetNig1 | grep -l --label=tetNig1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" xenTro2 | grep -l --label=xenTro2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" caePb2 | grep -l --label=caePb2 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" cb3 | grep -l --label=cb3 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" ce6 | grep -l --label=ce6 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" caeJap1 | grep -l --label=caeJap1 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" caeRem3 | grep -l --label=caeRem3 refGene
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "show tables;" priPac1 | grep -l --label=priPac1 refGene